### ISSUE TITLE
Runs on QNAP?

### ISSUE THREAD

**Issue by ammadz** [putdotio/putio-sync#23]
New to this; wondering if i can install this on a QNAP?

**Comment by cenkalti** [comment]
Never tried. As far as I know, QNAP runs on ARM processor. putio-sync itself is written in Go, and Go supports ARM: https://github.com/golang/go/wiki/GoArm

**Comment by ammadz** [comment]
thanks @cenkalti. Mine is running on Intel - will give it a try.
