### ISSUE TITLE
Runs on Synology ?

### ISSUE THREAD

**Issue by HAL9000000** [putdotio/putio-sync#24]
Works like a charm on my mac, bravo !
Wondering if i can install this on a Synology with an Intel 64-bit?

Is anybody working on a package .spk ?

Is there any dependancies ?

**Comment by igungor** [comment]
Glad you like it, thanks!

I don't know much about Synology packaging but it could be doable. There are no external dependencies. It's just a single executable binary, so it should be straightforward.
