### ISSUE TITLE
Cannot clear incomplete/failed downloads

### ISSUE THREAD

**Issue by ammadz** [putdotio/putio-sync#26]
cannot clear the failed downloads.

**Comment by ammadz** [comment]
@igungor Any update on this feature?

**Comment by igungor** [comment]
This request (and others) sounds reasonable. I'll definitely look into them.

**Comment by ammadz** [comment]
hi @igungor any progress here? thanks a lot

**Comment by ZerithZA** [comment]
Good day, anyone find a temporary solution for this?

**Comment by ndgold** [comment]
Also experiencing this issue. Is there a manual way to erase failed downloads that persist in the list after attempting to clear with the finished downloads button?
