### ISSUE TITLE
Setting to 'delete' file from the web after a successful sync

### ISSUE THREAD

**Issue by ammadz** [putdotio/putio-sync#30]

**Comment by igungor** [comment]
Do you mean actually delete the file from your computer or from Put.io?

**Comment by ammadz** [comment]
from Put.io. 
Would be good have that as an option, right?

**Comment by igungor** [comment]
I agree, but I'm not use if it should be file basis or for all files. I'll think about it. What do you think of setting an option to 'delete remote files after download' in settings?

**Comment by ammadz** [comment]
Great! That's exactly what I wanted. 
Tks

**Comment by igungor** [comment]
@tolgaakyuz can you add an option to the settings dialog to delete remote files?

"Delete original file" with a hint of "After a successful download" in the settings dialog would be nice.

The field the web ui should send is "delete-remotefile" to the config handler, along with the original config you send.

**Comment by bellwethr** [comment]
Is this functionality supposed to be working?  Syncing appears to work, but I don't see files consistently deleted.

**Comment by cenkalti** [comment]
Files should be deleted from put.io, after files are downloaded to computer if the checkbox is checked on setting. @bellwethr, is this the behavior that you expect?

**Comment by bellwethr** [comment]
That's the behavior I expect, but not what I see in practice.  All of the files in question are typically in subdirectories under the download directory -- I wonder if recursive deletion isn't handled?
