### ISSUE TITLE
Can't set the destination directory outside of the current user's home dir?

### ISSUE THREAD

**Issue by bellwethr** [putdotio/putio-sync#36]
The file tree browser for setting the destination directory starts in my home directory, and won't let me walk up the directory hierarchy.  I sync my files to a folder under /mnt, and need to be able to browse over.

I tried working around this by creating a symlink, but my symlink'ed directory doesn't show up in the file tree browser.

**Comment by cenkalti** [comment]
@bellwethr please reply if the problem is not solved.
