### ISSUE TITLE
Downloads appear to take an excessively long time.

### ISSUE THREAD

**Issue by bellwethr** [putdotio/putio-sync#37]
I can download a 1GB file from putio in < 10 minutes.  Downloading the same file with putio-sync takes over an hour.  Any suggestions on how to debug?

**Comment by cenkalti** [comment]
Hello @bellwethr. I still couldn't take look into this issue. Sorry for making you wait.

**Comment by ZerithZA** [comment]
I have the same problem. I dont have the fastest line ever but normally get 8Mbps to putio server. When using the putio-sync program I get between 2.4Mbps - 3.8Mbps when monitoring on my Mikrotik router although the Web browser reports 5MB's.
