### ISSUE TITLE
Cannot Load Local File Directory (Bug)

### ISSUE THREAD

**Issue by curreta** [putdotio/putio-sync#38]
## Steps To Repeat
- Installed on Windows 10 via Git command.
- Created Shortcut to C:\Projects\Go\bin\putio-sync.exe -server
- Ran above shortcut with admin rights
- Loaded: http://127.0.0.1:3000/
- Clicked `Destination Folder -> Change`
- The page hangs:
![screenshot-127 0 0 1 3000-2017-01-28-19-49-40](https://cloud.githubusercontent.com/assets/284943/22401507/eb1fbc1e-e592-11e6-8f3a-14cd8d1cbabc.png)

## Error
 - Getting 500 error on`open /: Access is denied.` on `http://127.0.0.1:3000/api/tree`

**Comment by barisergin** [comment]
I am getting the same exact error, also on Windows 10...  Console gives me this error:

client.js:841 GET http://127.0.0.1:3000/api/tree 500 (Internal Server Error)
