### ISSUE TITLE
Cannot get pass the authorisation

### ISSUE THREAD

**Issue by ammadz** [putdotio/putio-sync#42]
Hi guys,
For some reason I am unable to get pass the authorisation once after running the server. 
This is the error from the console:
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (config, line 0)
[Error] Unhandled promise rejection – null
	(anonymous function) (index.min.js:2:12404)
	D (index.min.js:2:11795)
	(anonymous function) (index.min.js:2:12275)
	exports (index.min.js:1:17139)
	(anonymous function) (index.min.js:2:15545)
	v (index.min.js:2:15403)
	g (index.min.js:2:15428)

If I restart the browser and visit 127.0.0.1 I get the web ui but I cannot save the settings or start the sync, errors from console then:
[Error] Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400) (list, line 0)
[Error] Unhandled promise rejection – Object
Object
	(anonymous function) (index.min.js:2:12404)
	D (index.min.js:2:11795)
	(anonymous function) (index.min.js:2:12275)
	exports (index.min.js:1:17139)
	(anonymous function) (index.min.js:2:15545)
	v (index.min.js:2:15403)
	g (index.min.js:2:15428)
[Error] Unhandled promise rejection – Object
Object
	(anonymous function) (index.min.js:2:12404)
	D (index.min.js:2:11795)
	(anonymous function) (index.min.js:2:12275)
	exports (index.min.js:1:17139)
	(anonymous function) (index.min.js:2:15545)
	v (index.min.js:2:15403)
	g (index.min.js:2:15428)
[Error] Failed to load resource: The network connection was lost. (list-downloads, line 0)
[Error] Unhandled promise rejection – Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
	(anonymous function) (index.min.js:2:12404)
	D (index.min.js:2:11795)
	(anonymous function) (index.min.js:2:12275)
	exports (index.min.js:1:17139)
	(anonymous function) (index.min.js:2:15545)
	v (index.min.js:2:15403)
	g (index.min.js:2:15428)

Thanks for your help.

**Comment by myronrodrigues** [comment]
I have this issue as well in Raspbian/Linux since last night.

**Comment by ammadz** [comment]
+1

**Comment by ammadz** [comment]
I am still on stuck here:

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (config, line 0)
[Error] Unhandled promise rejection – null
	(anonymous function) (index.min.js:2:12404)
	D (index.min.js:2:11795)
	(anonymous function) (index.min.js:2:12275)
	exports (index.min.js:1:17139)
	(anonymous function) (index.min.js:2:15545)
	v (index.min.js:2:15403)
	g (index.min.js:2:15428)

**Comment by ammadz** [comment]
some help here would be nice.. please.

**Comment by ammadz** [comment]
So this is not getting fixed then?

**Comment by myronrodrigues** [comment]
OK, I built the GO program from source lwc/putio-sync, but now the browse source folder won't load (spinning loader). 
`XMLHttpRequest cannot load https://put.io/v2/files/list?parent_id=0&breadcrumbs=true. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access. The response had HTTP status code 403.`
