### ISSUE TITLE
config.toml setup

### ISSUE THREAD

**Issue by bineyard** [putdotio/putio-sync#49]
How do I setup the config.toml file to utilize the username and password, instead of passing it with the command each time?

I put it as:
PUTIO_Username="[username]"
PUTIO_Password="[password]"

And I receive the error "empty username". I also tried without the quotes, and received some character error. These make me believe I'm configuring it incorrectly.

**Comment by berkanteber** [comment]
`PUTIO_` prefix is only for environment variables. Can you try without it (i.e. just `Username` and `Password`)?

**Comment by bineyard** [comment]
> `PUTIO_` prefix is only for environment variables. Can you try without it (i.e. just `Username` and `Password`)?

That worked!
